### ISSUE TITLE
[FEATURE] Trajectory Start Values

### ISSUE THREAD

**Issue by pulsipher** [pulsipher/InfiniteOpt.jl#43]
**Describe the feature you'd like**
Implement functionality to specify better start values for infinite variables. This will greatly help with convergence. 

**Does this pertain to a particular class of problems/techniques? If so explain.**
All infinite problems

**Describe what you currently do about this**
Only a single value can be used. Trajectories cannot be given.

**Additional context**
Perhaps it would be nice to implement some automatic methods.

**Comment by oameye** [comment]
Has this been implemented? How would you do it for a variable defined as follows?
```julia
@variables(model, begin
   x[1:2], Infinite(t)
end)
```

**Comment by pulsipher** [comment]
Yes, see https://infiniteopt.github.io/InfiniteOpt.jl/stable/guide/variable/#Variable-Start-Values

**Comment by oameye** [comment]
Thank you so much! Should have gone beyond the examples.
