### ISSUE TITLE
Revamp Macros with JuMP Dependencies

### ISSUE THREAD

**Issue by pulsipher** [pulsipher/InfiniteOpt.jl#60]
We need to change our macro structure to be devoid of internal JuMP function dependencies for better stability. It also appears we'll need to forego our convenient wrapping of `JuMP.@variable` within our macros. Please see the discussion here: https://github.com/jump-dev/JuMP.jl/issues/2333. Based on this discussion, it seems we'll need to decide between the two options:
1. Implement all the back-ending necessary to support our macros without the use of JuMP internal functions or `JuMP.@variable`. 
2. Drop most of our macros in favor of `JuMP.@variable` but with object orientated inputs (e.g., `@variable(m, y >= 0, Infinite(t, x))`) thus breaking our symbolic mathematical syntax.

**Comment by pulsipher** [comment]
#118 removed our dependencies on all of JuMP's internal functions except `JuMP.Containers._build_ref_sets` which will be more tedious to implement/maintain ourselves. The main difficulty here is that JuMP does not have a complete public API for constructors its container objects via extension macros.

**Comment by odow** [comment]
Nice write-up. I would write these as
```Julia
@variable(m, t in InfiniteParameter([0, 1]))
@variable(m, x[i=1:2] in InfiniteParameter(IntervalDomain([i, i+1])))
@variable(m, xi[1:2] in InfiniteParameter(MvNormal(u, s)))

@variable(m, a in FiniteParameter(42))
@variable(m, b[i=1:10] in FiniteParameter(vals[i]))

@variable(m, y[1:2] >= 0, InfiniteVariable(t, x))
@variable(m, y0[i=1:2] == 42, PointVariable(y, 0, [0, 0]))
@variable(m, z[1:2], Bin, ParameterBounds(t => IntervalDomain(0.5, 1)))

# This is scary. Do you have to use some invoke_latest magic?
@variable(m, d[i=1:N] in ParameterFunction((t,x) -> myfunc(t, x, a[i])))

Bounded Constsraint syntax??? I don't really understand what this is doing
```

**Comment by pulsipher** [comment]
Thanks for the quick response.  

The parameter functions don't need any `invokelatest` magic when an anonymous function is given like you show up above, but certain other cases (like the one in my example) we do have to use `invokelatest` to ensure it works. Note this syntax is experimental and hasn't been added yet to any official release.

Bounded constraints, simply denote constraints where we limit their scope to some sub-region of the infinite domain (e.g., boundary conditions, initial conditions, etc.).  For example, suppose we have a time infinite variable y(t) (whose reference is assigned to the Julia variable `y`)  and might want to enforce the following constraints:
```julia
julia> @constraint(m, c1, 2y <= 0) # builds constraint and enforces it over the full domains the intrinsic infinite parameters 
c1 : 3 y(t) ≤ 0.0, ∀ t ∈ [0, 10]

julia> @BDconstraint(m, c2(t == 0), y == 42) # builds a constraint enforced over the sub-domain t = 0
c2 : y(t) = 42.0, ∀ t = 0

julia> @BDconstraint(m, c3(t in [0, 5]), y^2 >= 2.2) # builds a constraint enforced over the bounded sub-domain t in [0, 5]
c3 : y(t)² ≥  2.2,  ∀ t ∈ [0, 5]

julia> @constraint(m, c4, y^2 >= 2.2, parameter_bounds = ParameterBounds(t => IntervalDomain(0, 5))) # equivalent to above
c4 : y(t)² ≥  2.2,  ∀ t ∈ [0, 5]
```

**Comment by odow** [comment]
Okay. It seems fair to support something like:
```julia
@constraint(model, y == 42, BoundaryCondition(t => 0))
@constraint(model, y == 42, IntervalDomain(t => [0, 5]))
```
This would let us "tag" constraints in the same way as variables. Want to open an issue in JuMP? It's probably quite a lot of work to implement so no promises on timeframe (unless you want to have a crack). The nice thing is adding these tags should be backward compatible, so it's not a blocker for JuMP 1.0.

**Comment by pulsipher** [comment]
That makes sense. Ya I can open an issue in JuMP to this effect, probably something tomorrow.

Thanks for the input.

**Comment by odow** [comment]
I'll add it to the list: https://github.com/jump-dev/JuMP.jl/issues/1938

**Comment by pulsipher** [comment]
Ok after more discussion, thought, and prototyping I believe the consensus will be the following.

Variables will be constructed via `@variable` using appropriate "tags".
```julia
# Infinite Variables (replaces `@infinite_variable`)
@variable(model, var_expr, Infinite(inf_params...), [set_args...], [kwargs...])

# Semi-Infinite Variables (new functionality)
@variable(model, var_expr, SemInfinite(inf_var, param_values...), [set_args...], [kwargs...])

# Point Variables (replaces `@point_variable`)
@variable(model, var_expr, Point(inf_var, param_values...), [set_args...], [kwargs...])

# Finite Variables (replaces `@hold_variable`)
@variable(model, var_expr, [set_args...], [kwargs...])

# Single Derivative Variables (replaces `@derivative_variable`)
@variable(model, var_expr, Deriv(inf_var, inf_param), [kwargs...])
``` 
Note that finite variable variables will no longer be associated with `ParameterBounds` (now called `DomainRestrictions`) since these can just be handled via constraints.

Infinite parameters could be extended using `@variable`, but this leads to a number of problems. Due to the need of additional keyword arguments and handling varied dimensional infinite domains the syntax would have to be one of the following:
```julia
@variable(model, param_expr in domain, InfiniteParameter, [kwargs...])

@variable(model, param_expr in InfiniteParameter(domain, [extra_kwargs...]), [jump_kwargs...]) 
```
These are not very intuitive for users, the nomenclature clashes with the rest of our abstraction (e.g., using the `set` keyword in the anonymous case to specify `domain` and using `@variable` for a parameter), and we would need to add quite a few errors checks to ensure none of the extra variable information/syntax is used. Thus, the tentative to plan is to fully revamp our `@infinite_parameter` macro and support our own macro-based container construction since that is really the only functionality we want from `@variable` in this use case:
```julia
@infinite_parameter(model, param_expr in [lb, ub], [kwargs..].)

@infinite_parameter(model, param_expr ~ distribution, [kwargs...])
```
This is more intuitive, concise, avoids the above problems, and is not a breaking change. Hopefully, JuMP will provide a public API for building containers in macros in the future.

Thus, with the `@finite_parameter` and `@parameter_function`  macros we'll maintain the current syntax since we'll have our own container construction API:
```julia
@finite_parameter(model, param_expr == value, [kwargs...])

@parameter_function(model, param_expr == func, [kwargs...])
```

Finally, we will discontinue `@BDconstraint` in favor of using JuMP's constraint macros:
```julia 
@constraint(model, name_expr, constr_expr, [DomainRestrictions(...)], [kwargs...])

@SDconstraint(model, name_expr, constr_expr, [DomainRestrictions(...)], [kwargs...])
```
Note that this change and a few others will enable us to finally support vector constraints.
