### ISSUE TITLE
[FEATURE] Quadrature with user-specific nodes

### ISSUE THREAD

**Issue by timueh** [pulsipher/InfiniteOpt.jl#86]
When solving integrals via quadrature, the nodes and weights are usually chosen based on the measure (e.g. Gauss-Hermite). For optimal control problems it may be useful to allow for considering specific nodes (e.g. points in time where a specific constraint should be satisfied). Hence, the quadrature rule should be able to incorporate user-given nodes, and then determine the remaining nodes and weights automatically.

A specific example of this is [Gauss-Radau quadrature](https://mathworld.wolfram.com/RadauQuadrature.html), for which the left end-point of the support is included.

Another example is [Gauss-Lobatto quadrature](https://mathworld.wolfram.com/LobattoQuadrature.html), for which both the lef and the right end-point of the support are included.

I can think of two possible ways to solve the problem

## Decompose integral

If certain points/nodes shall be included in the quadrature, the integral may be decomposed in as many parts as required. Then, Gauss-Lobatto can be applied to each part.

## Dedicated quadrature rule

[Section 2.3 from this paper](https://www.emis.de/journals/ETNA/vol.13.2002/pp119-147.dir/pp119-147.pdf) describes a generic method to do quadrature with user-given nodes.

**Comment by pulsipher** [comment]
Thank you for formalizing this feature request. It fits quite nicely with the discussion in #84 and I think will make for a very worthy contribution.

**Comment by Madeintheshade** [comment]
At one point time I used to do all of that low pass high pass all that stuff.

Without the original node that the base client was born, (not a substitute or a copy to try and mimic the original,s 1m of 2f of the original nodes) all you will end up doing is blinding the client  and ruining the optic. 

That's just my opinion. GL

**Comment by pulsipher** [comment]
@Madeintheshade, I don't think I quite understand what your comment is getting at.

**Comment by Madeintheshade** [comment]
Probably wouldn't believe it even if I told you haha

**Comment by Madeintheshade** [comment]
@pulsipher 
Probably wouldn't believe it even if I told you haha

**Comment by pulsipher** [comment]
Note that #107 was not actually merged as indicated above. Some strange GitHub glitch is to blame.

**Comment by timueh** [comment]
Anyway, does it mean you solved the issue? I'll take a look at the docs.. sweet!

**Comment by pulsipher** [comment]
This will be enabled once #114 is merged.
